---

resources:
- name: experiments
  type: git
  source:
    uri: https://github.com/dav1dc-pcf/chaostk-experiments.git
    branch: master
    submodules: all
    depth: 1
- name: chaostk-tasks
  type: git
  source:
    uri: https://github.com/dav1dc-pcf/chaostk-concourse-tasks.git
    branch: main
    submodules: all
    depth: 1

jobs:
- name: run-chaostk-turb-rand-experiment
  serial: true
  serial_groups: [ runchaostk ]
  plan:
  - in_parallel:
    - get: experiments
    - get: chaostk-tasks
  - task: run-chaostk-experiment-turbulence
    file: chaostk-tasks/tasks/run-chaostk-turb-rand/task.yml
    params:
      TURBULENCE_URL: ((turbulence_url))
      SITE_TO_TEST: ((site_to_test))
      DEPLOYMENT_NAME: ((deployment_name))
      NET_TIMEOUT: ((net_timeout))
      EXPERIMENT_FILE: ((experiment_file))
      CHAOSTK_CMD_FLAGS: ((chaostk_cmd_flags))
      RANDOM_JOB_NAME_ARR: ((random_job_name_arr))
      RANDOM_LIMIT_RANGE: ((random_limit_range))