---

resources:
- name: experiments
  type: git
  source:
    uri: https://github.com/dav1dc-pcf/chaostk-experiments.git
    branch: master
    submodules: all
    depth: 1
- name: chaostk-tasks
  type: git
  source:
    uri: https://github.com/dav1dc-pcf/chaostk-concourse-tasks.git
    branch: main
    submodules: all
    depth: 1

jobs:
- name: run-chaostk-cf-experiment
  serial: true
  serial_groups: [ runchaostk ]
  plan:
  - in_parallel:
    - get: experiments
    - get: chaostk-tasks
  - task: run-chaostk-experiment-cf
    file: chaostk-tasks/tasks/run-chaostk-cf/task.yml
    params:
      SITE_TO_TEST: ((site_to_test))
      EXPERIMENT_FILE: ((experiment_file))
      CHAOSTK_CMD_FLAGS: ((chaostk_cmd_flags))
      CF_API_URL: ((cf_api_url))
      CF_USERNAME: ((cf_username))
      CF_PASSWORD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_space))
      CF_APP_NAME: ((cf_app_name))