---

resources:
- name: experiments
  type: git
  source:
    uri: https://github.com/dav1dc-pcf/chaostk-experiments.git
    branch: main
    submodules: all
    depth: 1
- name: chaostk-tasks
  type: git
  source:
    uri: https://github.com/dav1dc-pcf/chaostk-concourse-tasks.git
    branch: main
    submodules: all
    depth: 1

jobs:
- name: run-chaostk-experiment
  serial: true
  serial_groups: [ runchaostk ]
  plan:
  - in_parallel:
    - get: experiments
    - get: chaostk-tasks
  - task: run-chaostk-experiment-turbulence
    image: dav1dc/chaostk-tanzu:0.0.2
    file: chaostk-tasks/tasks/run-chaostk-turb/task.yml
    params:
      TURBULENCE_URL: ((turbulence_url))
      SITE_TO_TEST: ((site_to_test))
      DEPLOYMENT_NAME: ((deployment_name))
      JOB_NAME: ((job_name))
      LIMIT: ((limit))
      NET_TIMEOUT: ((net_timeout))